# Refer to utils/config.py for definition and options.

version = "last_train"
wandb = false

[model]
trimap_channel = 3
mask_channel = 1
batch_size = 4
freeze_seg = true
self_refine_width1 = 30
self_refine_width2 = 15
    [model.arch]
    seg = "sam_vit_b"
    m2m = "sam_decoder_deep"

[train]
total_step = 30000
warmup_step = 500
val_step = 0
clip_grad = true
G_lr = 7e-5
rec_weight = 1.0
lap_weight = 1.0
# Uncomment to resume training
resume_checkpoint = "/app/checkpoints/0.5_for_os8_weigths_return_cousine_pre_train_grad_true_new_shedule_real_world_aug_full_data_sam_2_multiple_mask_True/model_step_8500"
reset_lr = true
lr_plateau_patience = 350


[data]
d646_fg = "datasets/Distinctions-646/Distinctions-646/Train/FG"
d646_pha = "datasets/Distinctions-646/Distinctions-646/Train/GT"
aim_fg = "/app/datasets/AIM-500-20250125T084537Z-001/AIM-500/original"
aim_pha = "/app/datasets/AIM-500-20250125T084537Z-001/AIM-500/mask"
# human2k_fg = "path/to/Human2K/Train/FG"
# human2k_pha = "path/to/Human2K/Train/Alpha"
am2k_fg = "/app/datasets/AM-2k-20250125T084638Z-001/AM-2k/train/fg"
am2k_pha = "/app/datasets/AM-2k-20250125T084638Z-001/AM-2k/train/mask"
rim_img = "/app/datasets/RefMatte/train/img"
rim_pha = "/app/datasets/RefMatte/train/prepare_mask"
coco_bg = "/app/datasets/coco_data/train2017"
bg20k_bg = "/app/datasets/BG-20k-20250125T085249Z-003/BG-20k/train"
workers = 8
crop_size = 1024
cutmask_prob = 0.25
pha_ratio = 0.5
augmentation = true
random_interp = true
real_world_aug = true

[log]
tensorboard_path = "./logs/tensorboard"
tensorboard_step = 100
tensorboard_image_step = 2000
logging_path = "./logs/stdout"
logging_step =  10
logging_level = "INFO"
checkpoint_path = "./checkpoints/"
checkpoint_step = 500
